##########################
## Actuator监控配置
##########################
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    env:
      enabled: true
##########################
## 基本配置
##########################
info:
  component: Config Server
server:
  port: 2100
spring:
  http:
    converters:
      preferred-json-mapper: jackson
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  application:
    name: smart-webfuse-cloud-service-config
  security:
    user:
      name: config-admin
      password: config-admin-pwd
  cloud:
    config:
      server:
        jdbc:  #通过数据库的方式
          sql: 'SELECT `KEY`, `VALUE` from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?'
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:config-db
    username: sa
    password:
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: jdbc
