##########################
## Actuator监控配置
##########################
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    env:
      enabled: true
##########################
## 基本配置
##########################
server:
  port: 8080
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true #开启负载均衡的重试机制
  http:
    converters:
      preferred-json-mapper: jackson
    encoding:
      charset: UTF-8
      enabled: true
      force: true
##########################
## eureka配置
##########################
eureka:
  client:
    healthcheck: true
    service-url:
      defaultZone: ${webfuse.eureka-server.urls}
  instance:
    prefer-ip-address: true
##########################
## ribbon配置（在这里配置了重试机制）
##########################
ribbon:
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 2 #重试负载均衡其他的实例最大重试次数,不包括首次server
  ConnectTimeout: 3000  #请求连接的超时时间
  ReadTimeout: 5000 #请求处理的超时时间
  ServerListRefreshInterval: 2000
  eager-load:
    enabled: true #开启饥饿加载(eager-load)模式
##########################
## Feign配置
##########################
feign:
  compression:  # 开启请求与响应的GZIP压缩
    request:
      enabled: true
    response:
      enabled: true
  hystrix:
    enabled: true

##########################
## Hystrix配置
##########################
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000  #断路器的超时时间需要大于ribbon的超时时间，不然不会触发重试
##########################
## 业务配置
##########################


########################################################################################################
---
spring:
  profiles: dev

webfuse:
  eureka-server:
    urls: http://eureka-admin:eureka-admin-pwd@localhost:2000/eureka/ #这里可以配置eureka的地址列表

########################################################################################################
---
spring:
  profiles: test

webfuse:
  eureka-server:
    urls: http://eureka-admin:eureka-admin-pwd@localhost:2000/eureka/ #这里可以配置eureka的地址列表

########################################################################################################
---
spring:
  profiles: beta

webfuse:
  eureka-server:
    urls: http://eureka-admin:eureka-admin-pwd@localhost:2000/eureka/ #这里可以配置eureka的地址列表

########################################################################################################
---
spring:
  profiles: prod

webfuse:
  eureka-server:
    urls: http://eureka-admin:eureka-admin-pwd@localhost:2000/eureka/ #这里可以配置eureka的地址列表

########################################################################################################