INSERT INTO "USER_INFO" ("ID","USERNAME","NICKNAME","TYPE","AVATAR","REGISTER_SOURCE","ACCOUNT_NON_EXPIRED","ACCOUNT_NON_LOCKED","CREDENTIALS_NON_EXPIRED","CREATE_TIME","UPDATE_TIME","STATUS","ENABLED")
VALUES ('680daf84-9720-470a-bb4c-68d31b916a48','zxguan','zxguan','1','','USER_NAME',FALSE,FALSE,FALSE,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'ENABLED',1);
INSERT INTO "USER_INFO" ("ID","USERNAME","NICKNAME","TYPE","AVATAR","REGISTER_SOURCE","ACCOUNT_NON_EXPIRED","ACCOUNT_NON_LOCKED","CREDENTIALS_NON_EXPIRED","CREATE_TIME","UPDATE_TIME","STATUS","ENABLED")
VALUES ('40b399ea-6cb1-4b4d-bfef-542424e488f7','hingkwan','hingkwan','1','','USER_NAME',FALSE,FALSE,FALSE,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'ENABLED',1);


INSERT INTO "ACTION" ("CODE","NAME","BIZ_TYPE","API_URL","ENABLED","DESCRIPTION","TAG","STATUS")
VALUES ('net.webfuse.uaa.user.UserController.getUserList','用户列表 [GET] /v0.1/users','','/v0.1/users',1,'用户列表','用户列表','ENABLED');
INSERT INTO "ACTION" ("CODE","NAME","BIZ_TYPE","API_URL","ENABLED","DESCRIPTION","TAG","STATUS")
VALUES ('net.webfuse.uaa.user.UserController.getUserById','用户详情 [GET] /v0.1/users/{id}','','/v0.1/users/{id}',1,'用户详情','用户详情','ENABLED');
INSERT INTO "ACTION" ("CODE","NAME","BIZ_TYPE","API_URL","ENABLED","DESCRIPTION","TAG","STATUS")
VALUES ('net.webfuse.uaa.user.UserController.deleteUserById','删除用户 [DELETE] /v0.1/users/{id}','','/v0.1/users/{id}',1,'删除用户','删除用户','ENABLED');
INSERT INTO "ACTION" ("CODE","NAME","BIZ_TYPE","API_URL","ENABLED","DESCRIPTION","TAG","STATUS")
VALUES ('net.webfuse.uaa.user.UserController.updateById','修改用户 [UPDATE] /v0.1/users/{id}','','/v0.1/users/{id}',1,'修改用户','修改用户','ENABLED');
INSERT INTO "ACTION" ("CODE","NAME","BIZ_TYPE","API_URL","ENABLED","DESCRIPTION","TAG","STATUS")
VALUES ('net.webfuse.uaa.user.UserController.createById','创建用户 [POST] /v0.1/users','','/v0.1/users',1,'创建用户','创建用户','ENABLED');

INSERT INTO "RESOURCE"("CLIENT_TYPE","CODE","NAME","TAG","STATUS","ENABLED","DESCRIPTION")
VALUES ('admin','admin_user_add_button','用户管理-添加用户','添加用户按钮','ENABLED',1,'添加用户按钮');
INSERT INTO "RESOURCE"("CLIENT_TYPE","CODE","NAME","TAG","STATUS","ENABLED","DESCRIPTION")
VALUES ('admin','admin_user_edit_button','用户管理-修改用户','修改用户按钮','ENABLED',1,'修改用户按钮');
INSERT INTO "RESOURCE"("CLIENT_TYPE","CODE","NAME","TAG","STATUS","ENABLED","DESCRIPTION")
VALUES ('admin','admin_user_del_button','用户管理-删除用户','删除用户按钮','ENABLED',1,'删除用户按钮');


INSERT INTO "PERMISSION"("CODE","NAME","STATUS","ENABLED")
VALUES('USER_MANAGER','用户管理','ENABLED',1);

INSERT INTO "ROLE" ("CODE","NAME","DESCRIPTION","SCOPE","STATUS","ENABLED")
VALUES('ADMINISTRATOR','管理员','admin','app','ENABLED',1);
INSERT INTO "ROLE"("CODE","NAME","DESCRIPTION","SCOPE","STATUS","ENABLED")
VALUES('USER','用户','user','app','ENABLED',1);


INSERT INTO "USER_ROLE"("USER_ID","ROLE_ID")
VALUES('96a59470-5879-4b12-8360-5e1575a6c1ae',1);
INSERT INTO "USER_ROLE"("USER_ID","ROLE_ID")
VALUES('96a59470-5879-4b12-8360-5e1575a6c1ae',2);
INSERT INTO "USER_ROLE"("USER_ID","ROLE_ID")
VALUES('40b399ea-6cb1-4b4d-bfef-542424e488f7',2);

INSERT INTO "ROLE_PERMISSION"("ROLE_ID","PERMISSION_ID")
VALUES(1,1);
INSERT INTO "ROLE_PERMISSION"("ROLE_ID","PERMISSION_ID")
VALUES(2,1);

INSERT INTO "PERMISSION_ACTION"("ACTION_ID","PERMISSION_ID")
VALUES(1,1);
INSERT INTO "PERMISSION_ACTION"("ACTION_ID","PERMISSION_ID")
VALUES(2,1);
INSERT INTO "PERMISSION_ACTION"("ACTION_ID","PERMISSION_ID")
VALUES(3,1);
INSERT INTO "PERMISSION_ACTION"("ACTION_ID","PERMISSION_ID")
VALUES(4,1);

INSERT INTO "PERMISSION_RESOURCE"("RESOURCE_ID","PERMISSION_ID")
VALUES(1,1);
INSERT INTO "PERMISSION_RESOURCE"("RESOURCE_ID","PERMISSION_ID")
VALUES(2,1);
INSERT INTO "PERMISSION_RESOURCE"("RESOURCE_ID","PERMISSION_ID")
VALUES(3,1);

