INSERT INTO "USER" ("USERNAME","PASSWORD","ACCOUNT_NON_EXPIRED","ACCOUNT_NON_LOCKED","CREDENTIALS_NON_EXPIRED","CREATE_TIME","UPDATE_TIME","ENABLED")
VALUES('admin','admin',1,1,1, CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),1);
INSERT INTO "USER" ("USERNAME","PASSWORD","ACCOUNT_NON_EXPIRED","ACCOUNT_NON_LOCKED","CREDENTIALS_NON_EXPIRED","CREATE_TIME","UPDATE_TIME","ENABLED")
VALUES('test','test',1,1,1, CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),1);

INSERT INTO "ACTION" ("NAME","DISPLAY_NAME","BIZ_TYPE","API_URL","ENABLED")
VALUES ('net.webfuse.uaa.user.UserController.getUserList','用户列表 [GET] /v0.1/users','','/v0.1/users',1);
INSERT INTO "ACTION" ("NAME","DISPLAY_NAME","BIZ_TYPE","API_URL","ENABLED")
VALUES ('net.webfuse.uaa.user.UserController.getUserById','用户详情 [GET] /v0.1/users/{id}','','/v0.1/users/{id}',1);
INSERT INTO "ACTION" ("NAME","DISPLAY_NAME","BIZ_TYPE","API_URL","ENABLED")
VALUES ('net.webfuse.uaa.user.UserController.deleteUserById','删除用户 [DELETE] /v0.1/users/{id}','','/v0.1/users/{id}',1);
INSERT INTO "ACTION" ("NAME","DISPLAY_NAME","BIZ_TYPE","API_URL","ENABLED")
VALUES ('net.webfuse.uaa.user.UserController.updateById','修改用户 [UPDATE] /v0.1/users/{id}','','/v0.1/users/{id}',1);
INSERT INTO "ACTION" ("NAME","DISPLAY_NAME","BIZ_TYPE","API_URL","ENABLED")
VALUES ('net.webfuse.uaa.user.UserController.createById','创建用户 [POST] /v0.1/users','','/v0.1/users',1);

INSERT INTO "RESOURCE"("CLIENT_TYPE","NAME","DISPLAY_NAME","TAG","ENABLED")
VALUES ('admin','admin_user_add_button','用户管理-添加用户','添加用户按钮',1);
INSERT INTO "RESOURCE"("CLIENT_TYPE","NAME","DISPLAY_NAME","TAG","ENABLED")
VALUES ('admin','admin_user_edit_button','用户管理-修改用户','修改用户按钮',1);
INSERT INTO "RESOURCE"("CLIENT_TYPE","NAME","DISPLAY_NAME","TAG","ENABLED")
VALUES ('admin','admin_user_del_button','用户管理-删除用户','删除用户按钮',1);


INSERT INTO "PERMISSION"("NAME","DISPLAY_NAME","STATUS","ENABLED")
VALUES('USER_MANAGER','用户管理','ENABLED',1);

INSERT INTO "ROLE"("ID","NAME","DISPLAY_NAME","SCOPE","ENABLED")
VALUES('929726219032068096','ADMINISTRATOR','管理员','admin',1);
INSERT INTO "ROLE"("ID","NAME","DISPLAY_NAME","SCOPE","ENABLED")
VALUES('929726219032199168','NORMAL_USER','普通用户','web',1);


INSERT INTO "USER_ROLE"("USER_ID","ROLE_ID")
VALUES(1,1);
INSERT INTO "USER_ROLE"("USER_ID","ROLE_ID")
VALUES(1,2);
INSERT INTO "USER_ROLE"("USER_ID","ROLE_ID")
VALUES(2,2);

INSERT INTO "ROLE_PERMISSION"("ROLE_ID","PERMISSION_ID")
VALUES(1,1);
INSERT INTO "ROLE_PERMISSION"("ROLE_ID","PERMISSION_ID")
VALUES(2,1);

INSERT INTO "PERMISSION_ACTION"("ACTION_ID","PERMISSION_ID")
VALUES(1,1);
INSERT INTO "PERMISSION_ACTION"("ACTION_ID","PERMISSION_ID")
VALUES(2,1);
INSERT INTO "PERMISSION_ACTION"("ACTION_ID","PERMISSION_ID")
VALUES(3,1);
INSERT INTO "PERMISSION_ACTION"("ACTION_ID","PERMISSION_ID")
VALUES(4,1);

INSERT INTO "PERMISSION_RESOURCE"("RESOURCE_ID","PERMISSION_ID")
VALUES(1,1);
INSERT INTO "PERMISSION_RESOURCE"("RESOURCE_ID","PERMISSION_ID")
VALUES(2,1);
INSERT INTO "PERMISSION_RESOURCE"("RESOURCE_ID","PERMISSION_ID")
VALUES(3,1);



